#!/bin/bash

# Configuration
script_name=steam-sel

# Abort on any error
set -e

# Ensure we have a runtime directory
test -n "$XDG_RUNTIME_DIR"

# Ensure SteamAppId is an integer
test "$SteamAppId" -eq "$SteamAppId"

f="$XDG_RUNTIME_DIR/$script_name/$SteamAppId"

echo "-- $0: f=$f"
echo "-- $0: PID is $$"

if [ -f "$f" ]
then
    echo "-- $0: overriding command with $f which contains:"
    script=$(cat "$f")
    echo "$script"
    rm -v "$f"
    eval "$script"
else
    echo "-- $0: running command from arguments:"
    echo "env $@"
    exec env "$@"
fi
