#!/usr/bin/python3
import os
import argparse
import subprocess

from operator import attrgetter

import re
import json

from xdg import BaseDirectory

from appinfolazy import AppinfoLazyDecoder
import vdf

#
# CONFIGURATION
#

# Your main Steam installation.
main_library = BaseDirectory.xdg_data_home + "/Steam"

# Your OS, according to Steam.
# Should be either linux, macos or windows.
# This script probably only works on linux anyway.
current_os = "linux"

# Your architecture, according to Steam.
# Should be either 32 or 64.
# AFAIK Steam is not even supported on i686 anymore, but whatever.
current_osarch = 64

# This is where we can find some info on compatibility tools.
# Change only if you know what you're doing. I don't.
steamplay_manifests_app_id = 891390

# This is your user ID to be substituted in $main_library/userdata/<id>.
# We need this because the launch options are stored below the userdata directory.
# If set to None, the script will try to use the "MostRecent" user, which we read
# from $main_library/config/loginusers.vdf
steam_user_id = None

# This is the script name. It is used as a subdirectory of $XDG_RUNTIME_DIR
# for storing temporary files. It must be the same in the corresponding loader script.
script_name = "steam-sel"

# This is the loader script name.
loader_script_name = script_name + "-loader"

# This is the loader script command. This should be included in the launch options.
# If the script is not in your path, you may want to set this to its absolute path.
loader_script_command = loader_script_name

# Output colors
color_normal = ""
color_error = "91"
color_warning = "33"
color_info = "94"
color_app_name = "93"
color_config_name = "92"

#
# END CONFIGURATION
#

# This is horrendous, but Steam apparently behaves this way,
# so I guess we will have to do the same. I'm deeply sorry.
def bash_escape(thing):
    return "'" + thing.replace("'","'\\''") + "'"

def setcolor(color):
    return "\033[" + ("0;" + str(color) if color is not None else "0") + "m"

apps = {}

# If steam_user_id is None, try to figure it out
if steam_user_id is None:
    with open(main_library + "/config/loginusers.vdf", "r") as loginusers_file:
        loginusers = vdf.load(loginusers_file)
    for userid, userdata in loginusers["users"].items():
        if int(userdata["MostRecent"]) == 1:
            # also we have to remove the higher 32 bits, for some reason
            steam_user_id = int(userid) & (1 << 32) - 1

print("steam_user_id =", steam_user_id)
if type(steam_user_id) is not int:
    print("steam_user_id is not an int, abort")
    exit(1)

# Create appinfo.vdf decoder
with open(main_library + "/appcache/appinfo.vdf", "rb") as appinfo_file:
    appinfo_raw = appinfo_file.read()
appinfo_decoder = AppinfoLazyDecoder(appinfo_raw)

# Load the main Steam config file. It contains the game <-> compatibility tool mappings.
with open(main_library + "/config/config.vdf", "r") as config_file:
    config_data = vdf.load(config_file)

# Load the user config file. It contains the per-game launch options.
with open(main_library + "/userdata/" + str(steam_user_id) + "/config/localconfig.vdf", "r") as user_config_file:
    user_config = vdf.load(user_config_file)

# Load the compatibility tool name <-> app_id mappings.
compat_tools_info = appinfo_decoder.decode(steamplay_manifests_app_id)["sections"][b"appinfo"][b"extended"][b"compat_tools"]
compat_app_id_to_name = {}
compat_name_to_app_id = {}
for name, data in compat_tools_info.items():
    name = name.decode()
    app_id = data[b"appid"].data
    compat_app_id_to_name[app_id] = name
    compat_name_to_app_id[name] = app_id

def get_compat_tool_appinfo(name):
    return compat_tools_info[name.encode()]

def parse_oslist(oslist):
    return set(oslist.split(",")) if oslist else set()

class App:
    def __init__(self, steamapps, app_id):
        self.app_id = app_id

        with open(steamapps + "/appmanifest_" + str(self.app_id) + ".acf") as appmanifest_file:
            self.appstate = vdf.load(appmanifest_file)["AppState"]

        self.name = self.appstate["name"]
        self.installdir = os.path.realpath(steamapps + "/common/" + self.appstate["installdir"])

        self.compat_tool = None
        if self.app_id in compat_app_id_to_name:
            try:
                self.compat_tool = CompatTool(self)
            except FileNotFoundError:
                print(self.app_id, self.name, "is a compatibility tool but has no toolmanifest.vdf")

    # FIXME: __repr__ should not be used this way
    def __repr__(self):
        s = setcolor(color_normal)
        s += "* "
        s += setcolor(color_app_name)
        s += self.name
        s += setcolor(color_normal)
        s += " (" + str(self.app_id) + "), " + self.installdir
        s += setcolor(None)
        return s

class CompatTool:
    def __init__(self, app):
        self.app = app

        with open(app.installdir + "/toolmanifest.vdf") as toolmanifest_file:
            toolmanifest = vdf.load(toolmanifest_file)["manifest"]

        self.commandline = toolmanifest["commandline"]
        try:
            self.require_tool_app_id = int(toolmanifest["require_tool_app_id"])
        except KeyError:
            self.require_tool_app_id = None

        compat_appinfo = get_compat_tool_appinfo(compat_app_id_to_name[self.app.app_id])
        self.from_oslist = parse_oslist(compat_appinfo[b"from_oslist"].decode())
        self.to_oslist = parse_oslist(compat_appinfo[b"to_oslist"].decode())

    def get_command(self, verb, cmd):
        cmd = bash_escape(self.app.installdir) + self.commandline.replace("%verb%", verb) + " " + cmd
        # FIXME ? compatibility tool stacking ignores the lower {from,to}_oslist.
        # Then again, I have no idea if Steam itself even cares.
        if self.require_tool_app_id:
            cmd = apps[self.require_tool_app_id].compat_tool.get_command(verb, cmd)
        return cmd

#
# Find Steam libraries
#

libraries = [main_library]

# Try and find other library folders.
# I think they are also available in main_library/config/config.vdf.
try:
    with open(main_library + "/steamapps/libraryfolders.vdf") as f:
        d = vdf.load(f)
        for k, v in d["LibraryFolders"].items():
            if k.isdigit():
                libraries.append(v)
except FileNotFoundError:
    print("libraryfolders.vdf not found")

print("Detected libraries:",libraries)

manifest_re = re.compile("^appmanifest_([0-9]+)\\.acf$")
for l in libraries:
    steamapps = l + "/steamapps"
    for e in os.listdir(steamapps):
        m = manifest_re.match(e)
        if m:
            app_id = int(m.group(1))
            apps[app_id] = App(steamapps, app_id)

l = []
for app_id, app in apps.items():
    if app.compat_tool:
        l.append(app.name)
print("Compatibility tools:", l)

def get_compat_tool_name_for_app(app_id):
    try:
        return config_data['InstallConfigStore']['Software']['Valve']['Steam']['CompatToolMapping'][str(app_id)]['name'] or None
    except KeyError:
        return None

# FIXME: appinfo should be embedded in app
# also, we don't need to laod all apps, only the one requested + compatibility tools
class LaunchEntry:
    def __init__(self, entry_id, app, appinfo, launch_config, launch_oslist, compat_tool=None, launch_options = None):
        self.id = entry_id

        self.app = app

        self.type = launch_config[b"type"].decode() if b"type" in launch_config else "none"

        self.description = launch_config[b"description"].decode() if b"description" in launch_config else self.app.name

        # Get the OS list from the launch config, if unavailable default to the app's,
        # if still unavailable it probably is windows-only.
        try:
            self.oslist = parse_oslist(launch_config[b"config"][b"oslist"].decode())
        except KeyError:
            try:
                self.oslist = parse_oslist(appinfo[b"common"][b"oslist"].decode())
            except KeyError:
                self.oslist = {"windows"}

        # Same for the architecture.
        try:
            self.osarch = launch_config[b"config"][b"osarch"]
        except KeyError:
            self.osarch = appinfo[b"common"].get(b"osarch") or b""

        # We need some more parsing, because some entries have it in a string, other in integer form.
        if type(self.osarch) is bytes:
            self.osarch = int(self.osarch) if self.osarch else None
        else:
            self.osarch = self.osarch.data

        # Get the beta key, if any.
        try:
            self.betakey = launch_config[b"config"][b"betakey"].decode()
        except KeyError:
            self.betakey = None

        # Get the working dir and executable name, which will be processed shortly after.
        try:
            self.workingdir = launch_config[b"workingdir"].decode()
        except KeyError:
            self.workingdir = None

        self.executable = launch_config[b"executable"].decode()

        # When running windows software on anything but windows, replace backslashes with the regular ones.
        if "windows" in (self.oslist or launch_oslist) and current_os != "windows":
            if self.workingdir:
                self.workingdir = self.workingdir.replace("\\", "/")
            self.executable = self.executable.replace("\\", "/")

        # Prepend the app install dir to the working dir, and default to it.
        if self.workingdir:
            self.workingdir = self.app.installdir + "/" + self.workingdir
        else:
            self.workingdir = self.app.installdir

        # Build the command.
        self.cmd = bash_escape(self.app.installdir + "/" + self.executable)

        # It seems we have to escape the backslashes.
        # I would like that to be the last stealth idiocy I have to deal with.
        if b"arguments" in launch_config:
            self.arguments = launch_config[b"arguments"].decode().replace("\\","\\\\")
            self.cmd += " " + self.arguments
        else:
            self.arguments = None

        # I have no idea what other verbs there may be. Steam seems to only use this one.
        if compat_tool:
            self.cmd = compat_tool.get_command("waitforexitandrun", self.cmd)

        if launch_options:
            if "%command%" in launch_options:
                self.cmd = launch_options.replace("%command%", self.cmd)
            else:
                self.cmd = self.cmd + " " + launch_options

    def as_bash_script(self):
        return "\n".join([
            "cd " + bash_escape(self.workingdir),
            "exec sh -c " + bash_escape(self.cmd),
            ''])

    def as_dict(self):
        return { "id": self.id,
                 "type": self.type,
                 "description": self.description,
                 "oslist": list(self.oslist),
                 "osarch": self.osarch,
                 "betakey": self.betakey,
                 "workingdir": self.workingdir,
                 "executable": self.executable,
                 "cmd": self.cmd,
                 }

    # FIXME: __repr__ should not be used this way
    def __repr__(self):
        def indentr(n, text):
            for i in range(n - len(text)):
                text += " "
            return text
        def indentl(n, text):
            spaces = ""
            for i in range(n - len(text)):
                spaces += " "
            return spaces + text

        reprwd = self.workingdir
        if reprwd == self.app.installdir:
            reprwd = "."
        elif reprwd.startswith(self.app.installdir + "/"):
            reprwd = reprwd[len(self.app.installdir) + 1:]

        s = setcolor(color_normal)
        s += indentl(6,"[" + str(self.id) + "] ")
        s += setcolor(color_config_name)
        s += self.description
        s += setcolor(color_normal)
        s += " | " + self.type + "\n"
        s += " " * 6 + "pwd=" + reprwd + "\n"
        s += " " * 6 + "exe=" + self.executable + "\n"
        s += " " * 6 + "args=" + (self.arguments or "")
        s += setcolor(None)
        return s
                #+ " " * 4 + "oslist=" + repr(self.oslist) + ",osarch=" + repr(self.osarch) + ",betakey=" + repr(self.betakey) + "\n" \

def get_commands(app_id, get_all=False):
    app = apps[app_id]

    compat_name = get_compat_tool_name_for_app(app_id)
    compat_app_id = compat_name_to_app_id.get(compat_name)
    compat_tool = apps[compat_app_id].compat_tool if compat_app_id else None


    launch_oslist = {current_os}
    if compat_tool:
        if current_os not in compat_tool.to_oslist:
            print("WARNING: Current OS:", current_os, "is not supported by", compat_tool_name, compat_to_oslist)

        launch_oslist = compat_tool.from_oslist


    local_app_config = user_config["UserLocalConfigStore"]["Software"]["Valve"]["Steam"]["Apps"]
    try:
        launch_options = local_app_config[str(app_id)]["LaunchOptions"]
    except KeyError:
        launch_options = ""

    print(app)
    print("  " + setcolor(color_normal) + "Compatibility tool: " + str(compat_tool.app.name if compat_tool else None) \
            +", OS:", launch_oslist)
    print("  Launch options:", repr(launch_options), setcolor(None))

    # TODO: fail on invalid launch options, add command line flag to ignore
    launch_options_suggestion = launch_options

    if "%command%" not in launch_options:
        if launch_options_suggestion:
            launch_options_suggestion = "%command% " + launch_options_suggestion
        else:
            launch_options_suggestion = "%command%"
        print(setcolor(color_warning) + "WARNING: Launch options do not contain %command%, override may not work." + setcolor(None))

    if loader_script_command not in launch_options:
        launch_options_suggestion = loader_script_command + " " + launch_options_suggestion
        print(setcolor(color_warning) + "WARNING: Launch options do not contain " + repr(loader_script_name) + ", override may not work." + setcolor(None))

    if launch_options_suggestion != launch_options:
        print(setcolor(color_info) + "NOTE: You may want to set your launch options to " + repr(launch_options_suggestion) + "." + setcolor(None))

    appinfo = appinfo_decoder.decode(app_id)["sections"][b"appinfo"]

    ignored_betakey = {}
    ignored_oslist = {}
    ignored_osarch = {}
    for launch_config_id, launch_config in appinfo[b"config"].get(b"launch",{}).items():
        launch_entry = LaunchEntry(int(launch_config_id), app, appinfo, launch_config, launch_oslist, compat_tool, launch_options)

        # Ignore launch entries associated with beta keys.
        # TODO support betas ?
        if not get_all and launch_entry.betakey:
            ignored_betakey[launch_entry.betakey] = ignored_betakey.get(launch_entry.betakey, 0) + 1
            continue

        # Ignore entries not corresponding to the launch OS (which may be altered by a compatibility tool).
        if not get_all and launch_entry.oslist and not launch_entry.oslist & launch_oslist:
            ignored_oslist[",".join(launch_entry.oslist)] = ignored_oslist.get(",".join(launch_entry.oslist), 0) + 1
            continue

        # Ignore entries from the wrong architecture. Yes, this includes 32-bit ones on a 64-bit OS.
        # Yes, many games including a 32-bit build usually have a "64-bit" entry to circumvent this.
        # Thanks Valve.
        if not get_all and launch_entry.osarch is not None and launch_entry.osarch != current_osarch:
            ignored_osarch[launch_entry.osarch] = ignored_osarch.get(launch_entry.osarch, 0) + 1
            continue

        yield (int(launch_config_id), launch_entry)

    if ignored_betakey:
        print("Ignored entries with beta keys: " + repr(ignored_betakey))
    if ignored_oslist:
        print("Ignored entries with OS: " + repr(ignored_oslist))
    if ignored_osarch:
        print("Ignored entries with arch: " + repr(ignored_osarch))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("app", nargs="?",
            help="Steam AppId or name of the game to run. Name matching is case-insensitive and does not require the full name. Without this argument, list the installed games.")
    parser.add_argument("config", nargs="?",
            help="Identifier of the launch config to use. Can be a numeric index or a type (default, server, config,…). When unspecified, list the available configs for app.")
    parser.add_argument("-n", "--dry-run", action="store_true",
            help="Display the command instead of running it")
    parser.add_argument("--analyze", action="store_true",
            help="Analyze all the games and report which are unlaunchable and which have multiple configurations.")
    args = parser.parse_args()

    # Analyze the whole library for unlaunchable and games with multiple config.
    if (args.analyze):
        allcmd = [(app_id, list(get_commands(app_id))) for app_id in apps.keys()]
        l1 = []
        l2 = []
        for app_id, cmds in allcmd:
            if len(cmds) == 0:
                l1.append((app_id, cmds))
            if len(cmds) > 1:
                l2.append((app_id, cmds))
        print()
        print("Unlaunchable games")
        print("------------------")
        for app_id, cmds in l1:
            print(apps[app_id])
        print()
        print("Games with multiple configurations")
        print("----------------------------------")
        for app_id, cmds in l2:
            print(apps[app_id])
            for i, c in cmds:
                print(c)
            print()

    # Display a list of applications.
    elif args.app is None:
        for app in sorted(apps.values(), key=attrgetter("name")):
            print(app)
    else:
        app_id = None
        try:
            app_id = int(args.app)
            app = apps[app_id]
        except ValueError:
            # try finding the app by name
            potential_apps = []
            # first try exact matches
            for app in apps.values():
                if args.app.lower() == app.name.lower():
                    potential_apps.append(app)
            # then try substrings
            if len(potential_apps) == 0:
                for app in apps.values():
                    if args.app.lower() in app.name.lower():
                        potential_apps.append(app)
            if len(potential_apps) == 1:
                app_id = potential_apps[0].app_id
        except KeyError:
            app_id = None
            potential_apps = None

        if app_id is None:
            if potential_apps:
                print(setcolor(color_error) + "ERROR: Game name " + repr(args.app) + " is ambiguous. The following games were matched:" + setcolor(None))
                for app in sorted(potential_apps, key=attrgetter("name")):
                    print(app)
                print(setcolor(color_error) + "ERROR: Please be more specific or use the AppId." + setcolor(None))
            else:
                print(setcolor(color_error) + "ERROR: Game " + repr(args.app) + " was not found." + setcolor(None))
            exit(1)

        # Display a list of available configurations.
        elif args.config is None:
            entries = list(get_commands(app_id))

            for entry_id, entry in entries:
                print(entry)

            #print(json.dumps(dict([(k, v.as_dict()) for k,v in entries])))

        # Run the game.
        else:
            entries = dict(get_commands(app_id))

            try:
                # Try by config ID.
                entry = entries[int(args.config)]
            except ValueError:
                # Try finding by type
                candidates = []
                for e in entries.values():
                    if e.type == args.config:
                        candidates.append(e)
                if len(candidates) == 0:
                    print(setcolor(color_error) + "ERROR: Config " + repr(args.config) + " was not found." + setcolor(None))
                    exit(1)
                if len(candidates) > 1:
                    print(setcolor(color_error) + "ERROR: Config type " + repr(args.config) + " is ambiguous. The following configs were matched:" + setcolor(None))
                    for c in candidates:
                        print(c)
                    print(setcolor(color_error) + "ERROR: Please use the numeric identifier instead." + setcolor(None))
                    exit(1)
                entry = candidates[0]

            print(entry)

            script = entry.as_bash_script()

            if args.dry_run:
                print(script)

            else:
                d = BaseDirectory.get_runtime_dir() + "/" + script_name
                if not os.path.isdir(d):
                    os.mkdir(d)
                p = d + "/" + str(app_id)
                with open(p, "w") as f:
                    f.write(script)
                subprocess.run(["steam", "-applaunch", str(app_id)])
